# Clang-CL (Windows Clang) flags
list(APPEND WSCOMMON_CLANG_CL_FLAGS
    "/W3"
    "/DNOMINMAX"
    "/DWIN32_LEAN_AND_MEAN"
    "/D_CRT_SECURE_NO_WARNINGS"
    "/D_SCL_SECURE_NO_WARNINGS"
    "/D_ENABLE_EXTENDED_ALIGNED_STORAGE"
    "/permissive-"
    "/Zc:__cplusplus"
    "/EHsc"
)

list(APPEND WSCOMMON_CLANG_CL_TEST_FLAGS
    "/W3"
    "/DNOMINMAX"
    "/DWIN32_LEAN_AND_MEAN"
    "/D_CRT_SECURE_NO_WARNINGS"
    "/D_SCL_SECURE_NO_WARNINGS"
    "/D_ENABLE_EXTENDED_ALIGNED_STORAGE"
    "/permissive-"
    "/Zc:__cplusplus"
    "/EHsc"
    "-Wno-deprecated-declarations"
    "-Wno-implicit-int-conversion"
    "-Wno-missing-prototypes"
    "-Wno-missing-variable-declarations"
    "-Wno-nullability-completeness"
    "-Wno-shadow"
    "-Wno-shorten-64-to-32"
    "-Wno-sign-compare"
    "-Wno-sign-conversion"
    "-Wno-unreachable-code-loop-increment"
    "-Wno-unused-function"
    "-Wno-unused-member-function"
    "-Wno-unused-parameter"
    "-Wno-unused-private-field"
    "-Wno-unused-template"
    "-Wno-used-but-marked-unused"
    "-Wno-gnu-zero-variadic-macro-arguments"
)

# GCC flags
list(APPEND WSCOMMON_GCC_FLAGS
    "-Wall"
    "-Wextra"
    "-Wcast-qual"
    "-Wconversion-null"
    "-Wformat-security"
    "-Wmissing-declarations"
    "-Wnon-virtual-dtor"
    "-Woverlength-strings"
    "-Wpointer-arith"
    "-Wundef"
    "-Wunused-local-typedefs"
    "-Wunused-result"
    "-Wvarargs"
    "-Wvla"
    "-Wwrite-strings"
    "-DNOMINMAX"
    "-fno-rtti"
)

list(APPEND WSCOMMON_GCC_TEST_FLAGS
    "-Wall"
    "-Wextra"
    "-Wcast-qual"
    "-Wconversion-null"
    "-Wformat-security"
    "-Wnon-virtual-dtor"
    "-Woverlength-strings"
    "-Wpointer-arith"
    "-Wundef"
    "-Wunused-local-typedefs"
    "-Wunused-result"
    "-Wvarargs"
    "-Wvla"
    "-Wwrite-strings"
    "-DNOMINMAX"
    "-fno-rtti"
    "-Wno-deprecated-declarations"
    "-Wno-missing-declarations"
    "-Wno-self-move"
    "-Wno-sign-compare"
    "-Wno-unused-function"
    "-Wno-unused-parameter"
    "-Wno-unused-private-field"
)

# LLVM/Clang flags
list(APPEND WSCOMMON_LLVM_FLAGS
    "-Wall"
    "-Wextra"
    "-Wc++98-compat-extra-semi"
    "-Wcast-qual"
    "-Wconversion"
    "-Wdeprecated-pragma"
    "-Wfloat-overflow-conversion"
    "-Wfloat-zero-conversion"
    "-Wfor-loop-analysis"
    "-Wformat-security"
    "-Wgnu-redeclared-enum"
    "-Winfinite-recursion"
    "-Winvalid-constexpr"
    "-Wliteral-conversion"
    "-Wmissing-declarations"
    "-Wnullability-completeness"
    "-Woverlength-strings"
    "-Wpointer-arith"
    "-Wself-assign"
    "-Wshadow-all"
    "-Wshorten-64-to-32"
    "-Wsign-conversion"
    "-Wstring-conversion"
    "-Wtautological-overlap-compare"
    "-Wtautological-unsigned-zero-compare"
    "-Wthread-safety"
    "-Wundef"
    "-Wuninitialized"
    "-Wunreachable-code"
    "-Wunused-comparison"
    "-Wunused-local-typedefs"
    "-Wunused-result"
    "-Wvla"
    "-Wwrite-strings"
    "-Wno-float-conversion"
    "-Wno-implicit-float-conversion"
    "-Wno-implicit-int-float-conversion"
    "-Wno-unknown-warning-option"
    "-Wno-unused-command-line-argument"
    "-DNOMINMAX"
    "-fno-rtti"
)

list(APPEND WSCOMMON_LLVM_TEST_FLAGS
    "-Wall"
    "-Wextra"
    "-Wc++98-compat-extra-semi"
    "-Wcast-qual"
    "-Wconversion"
    "-Wdeprecated-pragma"
    "-Wfloat-overflow-conversion"
    "-Wfloat-zero-conversion"
    "-Wfor-loop-analysis"
    "-Wformat-security"
    "-Wgnu-redeclared-enum"
    "-Winfinite-recursion"
    "-Winvalid-constexpr"
    "-Wliteral-conversion"
    "-Wmissing-declarations"
    "-Woverlength-strings"
    "-Wpointer-arith"
    "-Wself-assign"
    "-Wshadow-all"
    "-Wstring-conversion"
    "-Wtautological-overlap-compare"
    "-Wtautological-unsigned-zero-compare"
    "-Wthread-safety"
    "-Wundef"
    "-Wuninitialized"
    "-Wunreachable-code"
    "-Wunused-comparison"
    "-Wunused-local-typedefs"
    "-Wunused-result"
    "-Wvla"
    "-Wwrite-strings"
    "-Wno-float-conversion"
    "-Wno-implicit-float-conversion"
    "-Wno-implicit-int-float-conversion"
    "-Wno-unknown-warning-option"
    "-Wno-unused-command-line-argument"
    "-DNOMINMAX"
    "-fno-rtti"
    "-Wno-deprecated-declarations"
    "-Wno-implicit-int-conversion"
    "-Wno-missing-prototypes"
    "-Wno-missing-variable-declarations"
    "-Wno-nullability-completeness"
    "-Wno-shadow"
    "-Wno-shorten-64-to-32"
    "-Wno-sign-compare"
    "-Wno-sign-conversion"
    "-Wno-unreachable-code-loop-increment"
    "-Wno-unused-function"
    "-Wno-unused-member-function"
    "-Wno-unused-parameter"
    "-Wno-unused-private-field"
    "-Wno-unused-template"
    "-Wno-used-but-marked-unused"
    "-Wno-gnu-zero-variadic-macro-arguments"
)

# MSVC flags
list(APPEND WSCOMMON_MSVC_FLAGS
    "/W4"
    "/bigobj"
    "/permissive-"
    "/Zc:__cplusplus"
    "/EHsc"
    "/wd4005"
    "/wd4068"
    "/wd4180"
    "/wd4503"
    "/wd4800"
    "/DNOMINMAX"
    "/DWIN32_LEAN_AND_MEAN"
    "/D_CRT_SECURE_NO_WARNINGS"
    "/D_SCL_SECURE_NO_WARNINGS"
    "/D_ENABLE_EXTENDED_ALIGNED_STORAGE"
    "/GR-"
)

list(APPEND WSCOMMON_MSVC_LINKOPTS
    "-ignore:4221"
)

list(APPEND WSCOMMON_MSVC_TEST_FLAGS
    "/W3"
    "/bigobj"
    "/permissive-"
    "/Zc:__cplusplus"
    "/EHsc"
    "/wd4005"
    "/wd4068"
    "/wd4180"
    "/wd4503"
    "/wd4800"
    "/DNOMINMAX"
    "/DWIN32_LEAN_AND_MEAN"
    "/D_CRT_SECURE_NO_WARNINGS"
    "/D_SCL_SECURE_NO_WARNINGS"
    "/D_ENABLE_EXTENDED_ALIGNED_STORAGE"
    "/GR-"
    "/wd4018"
    "/wd4101"
    "/wd4244"
    "/wd4267"
    "/wd4996"
)

list(APPEND WSCOMMON_CRYPTO_X64_FLAGS
    "-maes"
    "-msse4.1"
    "-msse4.2"
    "-mavx"
    "-mavx2"
)

list(APPEND WSCOMMON_CRYPTO_MSVC_X64_FLAGS
    "/arch:AVX2"
)

list(APPEND WSCOMMON_CRYPTO_ARM64_FLAGS
    "-march=armv8-a+crypto"
)

list(APPEND WSCOMMON_CRYPTO_ARM32_FLAGS
    "-mfpu=crypto-neon-fp-armv8"
)
